# Generated by Django 3.0.3 on 2020-07-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_listings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='value_offer',
            field=models.DecimalField(decimal_places=2, help_text='How much are you willing to pay for this item?', max_digits=8),
        ),
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.CharField(blank=True, help_text='Again, not required, but this could help your product gain the spotlight it deserves! Examples of categories include Fashion, Toys, Electronics, Home, etc.', max_length=64),
        ),
        migrations.AlterField(
            model_name='listings',
            name='description',
            field=models.CharField(help_text="A longer description that lets users know more about what you're selling!", max_length=2048),
        ),
        migrations.AlterField(
            model_name='listings',
            name='image_url',
            field=models.CharField(blank=True, help_text='This is not required, but if you want to include an image for your product, please include an online url for it here!', max_length=2048),
        ),
        migrations.AlterField(
            model_name='listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, help_text='What is the starting price you want to sell your product for? All prices are in USD!', max_digits=8),
        ),
        migrations.AlterField(
            model_name='listings',
            name='title',
            field=models.CharField(help_text='The title to be displayed for the listing', max_length=64),
        ),
    ]
