# Generated by Django 3.0.3 on 2020-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_listings_closed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
